dist: focal # versao unbumtu
language: node_js
node_js:
  - "18"  # versao do node mais antiga suportada 

cache:
  directories:
    - node_modules  # Cache para acelerar a instalação de dependências

install:
  - npm install  # Instala as dependências do projeto

script:
  - npm run build  # Compila o TypeScript
  - npm test       # Executa os teste